### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jffsx** [suitmedia/laravel-cacheable#17]
Hi friend,

First congratulations for the package. I'd like some help.

Is there any way to implement it so that it is transparent to application? In the example of the documentation I have to pass my repository through the wrap `\Cacheable::wrap(ArticleRepository::class);`

My problem is that the repositories in my application are injected into services (Service Layer Pattern) by dependency injection

My repository extends the repository pattern:

```
class LeadRepository extends Repository implements RepositoryContract
{
    / **
     * Specify model class name
     *
     * @return string
     * /
    public function model ()
    {
        return Lead::class;
    }
}
```

Laravel Bind:

```
$this->app->bind(
    Repositories\Contracts\LeadRepository::class,
    Repositories\LeadRepository::class
);
```

In services:

```
use Imovs\Auth\Domains\Leads\Repositories\Contracts\LeadRepository;

public function __construct(LeadRepository $repository)
{
    $this->repository = $repository;
}
```

Was there any way I did not have to change the whole application? 
Any way for my repositories to extend the cache package?

I could not think of anything, if you can help me I thank you.

**Comment by richan-fongdasen** [comment]
Hi @jffsx ,

Thanks for having an interest to use this package.

This package uses a dynamic decorator class that can wrap any repository object and add the automatic cache behaviour to its public methods. However, the repository object should implement `CacheableRepository` contract/interface to make this package works as documented.

According to your sample code in services, i think you can use this approach:

```php
use Imovs\Auth\Domains\Leads\Repositories\Contracts\LeadRepository;

class SomeService
{
    protected $repository;

    public function __construct(LeadRepository $repository)
    {
        $this->repository = \Cacheable::wrap($repository);
    }
}
```

Actually, i noticed a conflict in your code that would lead to incompatibility with this package. It seems like your repository pattern and this package do not use same interface.

Your RepositoryContract declare `model()` method that should return model classname (string).

```php
class LeadRepository extends Repository implements RepositoryContract
{
    / **
     * Specify model class name
     *
     * @return string
     * /
    public function model()
    {
        return Lead::class;
    }
}
```

But in this package, CacheableRepository contract declare `model()` method that should return `CacheableModel` interface.
https://github.com/suitmedia/laravel-cacheable/blob/master/src/Contracts/CacheableRepository.php#L47

i would like to recommend you to fix the conflict first, before you can use this package.

**Comment by jffsx** [comment]
Hi @richan-fongdasen ,

Regarding the implementation of the `CacheableRepository` I did the implementation in my abstract repository (all repositories extend it) and also followed the documentation

```php
abstract class Cacheable extends Repository implements CacheableRepository
{
     use CacheableTrait;
     ...
```

And in that same class I overwritten the `cacheTags` method to create the model according to my implementation, basically this

```php
if (is_string($model)) {
    $model = \App::make($model);
}
```

I used this override in my `$this->repository = \Cacheable::wrap($repository);` and worked perfectly

The idea of the help request was to try to somehow abstract this (I could not think of anything lol) so I did not have to change all the services of the 5 projects that I will implement the package, something that abstract add remove the cache of a certain repository

Anyway thank you very much for your attention.
